name: Mac Testing
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: macos-15
        steps:
            - uses: actions/checkout@v2
            # Python 3.13.1 pre-installed (https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md)
            - uses: actions/setup-python@v5
              with:
                python-version: '3.13' 
            - name: Install dependencies
            # Create venv, update pip, install pytest, install requirements, install current pallas
            # TODO: Increment pallas version number by +0.0.1 if there's an existing [major].[minor][.0] build on GitHub's Releases tab before this step
            # TODO: Auto-publish to GitHub's Releases tab
              run: |
                python3.13 -m venv .venv
                source .venv/bin/activate
                python3.13 -m pip install --upgrade pip
                python3.13 -m pip install pytest
                python3.13 -m pip install -r requirements.txt
                python3.13 -m pip install . --no-cache-dir
            - name: Run tests with pytest
              run: |
                source .venv/bin/activate
                cd tests
                pytest